plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
    id 'com.gradleup.shadow'
}

//configurations {
//    shade
//    implementation.extendsFrom shade
//}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    
    shadow 'com.electronwill.night-config:toml:3.6.0'
}

tasks.named('shadowJar', com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) {
    configurations = project.configurations.named('shadow').map { [it] }

    relocate 'com.electronwill.nightconfig', 'io.github.jason13official.disenchanting_table.shadow.nightconfig'
    // archiveClassifier.set('')
}

jar {
    dependsOn shadowJar
    mustRunAfter shadowJar
}

loom {
    def aw = project(':fabric').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
    mods {
        "disenchanting_table" {
            sourceSet sourceSets.main
            configuration configurations.shadow
        }
    }
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}
